// https://projecteuler.net/problem=2
// Euler #2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.


let myCurrentNumber = 2;
let myPreviousNumber = 1;
const minNumber = 0;
const maxNumber = 89;

console.log(myPreviousNumber);
console.log(myCurrentNumber);

while ( (myPreviousNumber + myCurrentNumber) <= maxNumber)
{
	myCurrentNumber = myPreviousNumber + myCurrentNumber;
	myPreviousNumber = myCurrentNumber - myPreviousNumber;
	console.log(myCurrentNumber);

}
